# -*- coding: utf-8 -*-
"""Novel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ziPJKO_NaCZgLwTZHZCnCZOImE3CGRnh
"""

text = """
Fahoo forays, dahoo dorays
Welcome Christmas, bring your light
Fahoo forays, dahoo dorays
Welcome in the cold of night

Welcome Christmas, fahoo ramus
Welcome Christmas, dahoo damus
Welcome Christmas, while we stand
Heart to heart and hand in hand



Trim up the tree with Christmas stuff
Like bingle balls and whofoo fluff
Trim up the town with googoo gums
And bizilbigs and wums

Trim every blessed window and trim every blessed door
Hang up whoboohoo bricks then run out and get some more!
Hang pantookas on the ceilings
Pile panpoonas on the floor
Trim every blessed needle on the blessed Christmas tree
Christmas comes tomorrow. Trim you, trim me!
Trim up your tree with fuzzle fuzz
And fliffer bloofs, and wuzzle wuzz
Trim up your uncle and your aunt
With yards of whoflut flay


Every Who down in Whoville liked Christmas a lot
But the Grinch who lived just North of Whoville did not!

The Grinch hated Christmas! The whole Christmas season!
Now, please don't ask why. No one quite knows the reason.

It could be, perhaps, that his shoes were too tight.
It could be his head wasn't screwed on just right.

But I think that the most likely reason of all
May have been that his heart was two sizes too small.

But, whatever the reason, his heart or his shoes,
He stood there on Christmas Eve hating the Whos,

Staring down from his cave with a sour, Grinchy frown
At the warm lighted windows below in their town,

For he knew every Who down in Whoville beneath
Was busy now hanging a hollywho wreath.

"And they're hanging their stockings," he snarled with a sneer.
"Tomorrow is Christmas! It's practically here!"

Then he growled, with his Grinch fingers nervously drumming,
"I must find some way to keep Christmas from coming!

For, tomorrow, I know all the Who girls and boys
Will wake bright and early. They'll rush for their toys!

And then! Oh, the noise! Oh, the noise! Noise! Noise! Noise!
There's one thing I hate! All the NOISE! NOISE! NOISE! NOISE!

And they'll shriek squeaks and squeals, racing 'round on their wheels.
They'll dance with jingtinglers tied onto their heels.
They'll blow their floofloovers. They'll bang their tartookas.
They'll blow their whohoopers. They'll bang their gardookas.
They'll spin their trumtookas. They'll slam their slooslunkas.
They'll beat their blumbloopas. They'll wham their whowonkas.
And they'll play noisy games like zoozittacarzay,
A roller-skate type of lacrosse and croquet!
And then they'll make ear-splitting noises galooks
On their great big electro whocarnio flooks!

Then the Whos, young and old, will sit down to a feast.
And they'll feast! And they'll feast! And they'll FEAST! FEAST! FEAST! FEAST!

They'll feast on Who pudding, and rare Who roast beast,
Raw roast beast is a feast I can't stand in the least!

And then they'll do something I hate most of all!
Every Who down in Whoville, the tall and the small,

They'll stand close together, with Christmas bells ringing.
They'll stand hand-in-hand, and those Whos will start singing!"

Fahoo forays, dahoo dorays
Welcome Christmas! Come this way
Fahoo forays, dahoo dorays
Welcome Christmas, Christmas Day

Welcome, welcome, fahoo ramus
Welcome, welcome, dahoo damus
Christmas Day is in our grasp
So long as we have hands to clasp

Fahoo forays, dahoo dorays...


"And they'll sing! And they'll sing! And they'd SING! SING! SING! SING!"
And the more the Grinch thought of this Who Christmas Sing,
The more the Grinch thought, "I must stop this whole thing!

Why for fifty-three years I've put up with it now!
I must stop Christmas from coming! But how?"

Then he got an idea! An awful idea!
The Grinch got a wonderful, awful idea!

"I know just what to do!" The Grinch laughed in his throat.
"I'll make a quick Santy Claus hat and a coat."

And he chuckled, and clucked, "What a great grinchy trick!
With this coat and this hat, I'll look just like Saint Nick!"

You're a mean one, Mr. Grinch. You really are a heel.
You're as cuddly as a cactus. You're as charming as an eel.
Mr. Grinch! You're a bad banana with a greasy black peel!

You're a monster, Mr. Grinch. Your heart's an empty hole.
Your brain is full of spiders. You've got garlic in your soul.
Mr. Grinch! I wouldn't touch you with a thirty-nine-and-a-half foot pole!


"All I need is a reindeer." The Grinch looked around.
But since reindeer are scarce, there was none to be found.

Did that stop the Grinch? Hah! The Grinch simply said,
"If I can't find a reindeer, I'll make one instead!"

So he took his dog Max, and he took some black thread.
And he tied a big horn on top of his head.

Then he loaded some bags and some old empty sacks
On a ramshackle sleigh and he whistled for Max.

Then the Grinch said "Giddyap!" and the sleigh started down
Toward the homes where the Whos lay a-snooze in their town.

All their windows were dark. No one knew he was there.
All the Whos were all dreaming sweet dreams without care
When he came to the first little house of the square.

"This is stop number one," the old Grinchy Claus hissed,
As he climbed to the roof, empty bags in his fist.

Then he slid down the chimney, a rather tight pinch.
But if Santa could do it, then so could the Grinch.

He got stuck only once, for a minute or two.
Then he stuck his head out of the fireplace flue

Where the little Who stockings hung all in a row.
"These stockings," he grinched, "are the first things to go!"

Then he slithered and slunk, with a smile most unpleasant,
Around the whole room, and he took every present!

Pop guns, pampoogas, pantookas, and drums!
Checkerboards, bizilbigs, popcorn, and plums!

And he stuffed them in bags. Then the Grinch, very nimbly,
Stuffed all the bags, one by one, up the chimney.

You're a vile one, Mr. Grinch. You have termites in your smile.
You have all the tender sweetness of a seasick crocodile.
Mr. Grinch! Given the choice between the two of you I'd take the seasick crocodile!

You're a rotter, Mr. Grinch. You're the king of sinful sots.
Your heart's a dead tomato splotched with moldy purple spots.
Mr. Grinch! You're a three decker sauerkraut and toadstool sandwich with arsenic sauce!


Then he slunk to the icebox. He took the Whos' feast!
He took the Who pudding! He took the roast beast!

He cleaned out that icebox as quick as a flash.
Why, that Grinch even took the last can of Who hash!

Then he stuffed all the food up the chimney with glee.
"Now," grinned the Grinch, "I will stuff up the tree!"

As the Grinch took the tree, as he started to shove,
He heard a small sound like the coo of a dove.

He turned around fast, and he saw a small Who!
Little Cindy-Lou Who, who was no more than two.

She stared at the Grinch and said, "Santy Claus, why,
Why are you taking our Christmas tree? Why?"

But, you know, that old Grinch was so smart and so slick,
He thought up a lie, and he thought it up quick!

"Why, my sweet little tot," the fake Santy Claus lied,
"There's a light on this tree that won't light on one side.

So I'm taking it home to my workshop, my dear.
I'll fix it up there, then I'll bring it back here."

And his fib fooled the child. Then he patted her head,
And he got her a drink, and he sent her to bed.

And when Cindy-Lou Who was in bed with her cup,
He crupt to the chimney and stuffed the tree up!

Then he went up the chimney himself, the old liar.
And the last thing he took was the log for their fire.
On their walls he left nothing but hooks and some wire.

And the one speck of food that he left in the house
Was a crumb that was even too small for a mouse.

Then he did the same thing to the other Whos' houses,
Leaving crumbs much too small for the other Whos' mouses!

You nauseate me, Mr. Grinch, with a nauseous super "naus"!
You're a crooked dirty jockey and you drive a crooked hoss.
Mr. Grinch! Your soul is an appalling dump heap overflowing with the most disgraceful assortment of rubbish imaginable mangled up in tangled up knots!

You're a foul one, Mr. Grinch. You're a nasty-wasty skunk.
Your heart is full of unwashed socks. Your soul is full of gunk.
Mr. Grinch! The three words that best describe you are as follows, and I quote, "Stink, stank, stunk"!


It was quarter of dawn. All the Whos still a-bed,
All the Whos still a-snooze, when he packed up his sled,

Packed it up with their presents, their ribbons, their wrappings,
Their snoof and their fuzzles, their tringlers and trappings!

Ten thousand feet up, up the side of Mount Crumpet,
He rode with his load to the tiptop to dump it!

"Pooh-pooh to the Whos!" he was grinchily humming.
"They're finding out now that no Christmas is coming!

They're just waking up! I know just what they'll do!
Their mouths will hang open a minute or two
Then the Whos down in Whoville will all cry boo-hoo!

That's a noise," grinned the Grinch, "that I simply must hear!"
He paused, and the Grinch put a hand to his ear.

And he did hear a sound rising over the snow.
It started in low, then it started to grow.

Fahoo forays, dahoo dorays
Welcome Christmas! Come this way
Fahoo forays, dahoo dorays
Welcome Christmas, Christmas Day

Welcome, welcome, fahoo ramus
Welcome, welcome, dahoo damus
Christmas Day is in our grasp
So long as we have hands to clasp


But this sound wasn't sad!
Why, this sound sounded glad!

Every Who down in Whoville, the tall and the small,
Was singing without any presents at all!

He hadn't stopped Christmas from coming! It came!
Somehow or other, it came just the same!

And the Grinch, with his grinch feet ice-cold in the snow,
Stood puzzling and puzzling. "How could it be so?

It came without ribbons! It came without tags!
It came without packages, boxes, or bags!"

He puzzled and puzzed till his puzzler was sore.
Then the Grinch thought of something he hadn't before.

Maybe Christmas, he thought, doesn't come from a store.
Maybe Christmas, perhaps, means a little bit more!

And what happened then? Well, in Whoville they say
That the Grinch's small heart grew three sizes that day!

And then the true meaning of Christmas came through,
And the Grinch found the strength of ten Grinches, plus two!

And now that his heart didn't feel quite so tight,
He whizzed with his load through the bright morning light

With a smile to his soul, he descended Mount Crumpet
Cheerily blowing "Who! Who!" on his trumpet.

He road into Whoville. He brought back their toys.
He brought back their floof to the Who girls and boys.

He brought back their snoof and their tringlers and fuzzles,
Brought back their pantookas, their dafflers and wuzzles.

He brought everything back, all the food for the feast!
And he, he himself, the Grinch carved the roast beast!

Welcome Christmas. Bring your cheer,
Cheer to all Whos, far and near.

Christmas Day is in our grasp
So long as we have hands to grasp.

Christmas Day will always be
Just as long as we have we.

Welcome Christmas while we stand
Heart to heart and hand in hand.

For as long as can be remembered,

storks delivered babies

from their perch on Stork Mountain.

It was an honor and a privilege to serve.

It was our duty, our core belief,

the driving force of our very lifeblood.

Aw... Ow!

It wasn't always easy.

Oh...

This was our challenge.

This was our sacred duty.

No matter how tough or impossible

or brutal or harsh or inhumane or savage,

we would triumph over adversity.

Phew!

Gotcha!

Oh!

Hey.

- On your right.

- Left.

Bike lane.

Thank goodness we don't do that anymore.

There! Right there!

The problem was, we had the wrong cargo.

Our new phones!

Luckily, now, storks deliver

packages for Cornerstore.com!

- My dude!

- Oh, yeah!

Yo, Kevron! Lookin' good, my man!

Oh, I love this guy!

Perfect landing. Chiggy-check.

You're the man!

What? Millionth package? Not possible.

I thought I was only at 20.

Hey, Junior, are you gonna celebrate?

You know what? You're right.

I should celebrate.

What are you guys doing this weekend?

Are you guys free?

The wife and I

are celebrating another anniversary.

Got my kid's game this weekend.

Family reunion. The whole family's coming.

Oh. Just wanted to confirm.

That you were all busy.

I assumed you were all busy and you are.

So, if anything changes, let me know.

I maybe could get out of work.

Probably can't,

but let me know if you can.

Great job out there, brah!

Thanks, Pigeon Toady.

Check out my girlfriend.

- She's in Canada.

- Yeah-huh.

She migrated.

- She's not made up.

- Okay.

Look at her! Look at her!

- She exists, brah!

- That's great.

Hey, did you guys hear about Roger?

Ah!

Oh, my goodness. Are you okay?

What? Hey, brah. I say... What? Okay.

I tell you about my girlfriend?

Hey, boss wants to see you.

Uh...

Hunter wants to see me?

All right. Head in the game, Junior.

So, you're Hunter.

What do you do around here?

No, I hate that.

Hunter. Nice. To. Meet. You.

No, that's too robot.

Just say it normal. Just say it normal.

Here we go.

Nice to meet you!

What is wrong with me?

Junior.

Hunter.

You know why

I built my office entirely out of glass

even though birds can't see glass?

I do not.

Power move.

Eighteen years ago, I saved all storks

by getting out of babies

and into package delivery.

Now, this Monday at Storkcon, the board

will announce they're kicking me upstairs.

I'm going to be named Chairman.

Which means you are going to be named

boss.

Boss!

Cool, cool, cool. Very cool, very cool.

Now, look upon your domain

with your eyes wide open.

- Yeah.

- Wider.

I love it. Feels good.

How can you be boss

if you can't look at it?

If I go blind, it was worth it.

You know the hardest thing

about bein' boss?

Staring at the sun?

No, this is easy.

Whether to be like a friend boss

or a distant, weird boss?

Always be distant and weird.

What's the matter with you?

Sorry.

No, it's dealing with that.

The orphan Tulip?

I don't understand.

Do you know why

we stopped delivering babies?

Because there are so many

other ways of getting babies?

Yes. But that's not the whole story.

Eighteen years ago,

when we still delivered human infants,

a stork named Jasper

went crazy and tried to keep a baby.

Tulip's beacon broke.

Her address was destroyed,

so we could no longer deliver her.

My baby!

It was then I realized that

there was no future in baby delivery.

Now, the orphan Tulip has just turned 18,

which means we can finally liberate her

and return her to the human world.

But she's no trouble.

Oh, she isn't, is she?

Here's our profit chart.

- I love a good profit chart.

And cut!

- Wow. That was so amazing!

- Walter, you did a wonderful job.

Thank you, Kermit. Did we get that?

- We got it.

- We got it, yup.

Movie's over, people.

Go home. That is a wrap.

Okay, nice work, everyone.

Make sure to fill out your I-9s,

and we'll see you on the next one.

So... What do we do now?

Well, we're together again.

We got the theater

and all our fans are back.

Yeah!

Actually, those were extras.

I saw a few tapping their toes.

Yeah, those were paid dancers.

Or...

Maybe since we're all here,

now could be the perfect time

for you and me to tie the knot, Kermie!

Well, I mean, maybe I could.

Hey, what's the camera still doing here?

Oh, no. Disaster!

That can only mean one thing.

Doggone it, you're right!

It looks like they've ordered a sequel.

We're doing a sequel

We're back by popular demand

Come on, everybody,

strike up the band!

We're doing a sequel

That's what we do in Hollywood

And everybody knows

That the sequel's never quite as good

A sequel

Another feature attraction

Places, please

Light the lights

Roll camera, "Action!"

I thought it was the end

But no, my friends, this is when

We get to do it all again!

Do it all again

Until the credits roll

We got another go to show them

We can do it all again!

We're doing a sequel

There's no need to disguise

The studio considers us

a viable franchise

We're doing a sequel

The studio wants more

While they wait for Tom Hanks

To make Toy Story 4!

I thought it was the end

But no, my friends, this is when

We get to do it all again!

Do it all again!

Until the credits roll

We've got another go to show them

We can do it all again!

We're doing a sequel

Let's give it a go

With Hollywood stars

And more one-liner cameos

We're doing a sequel

I don't mean to be a stickler

But this is the seventh sequel

To our original motion picture

We're doing a sequel

Let's give it a shot

All we need now is a half-decent plot

Got it. An epic love story

between a very handsome,

long-nosed purple thing

and a beautiful chicken.

Gonzo with the Wind.

Does anybody have any other ideas?

It's about getting the Muppets

back together again

to stop an evil oil baron

from demolishing the old studio!

Fozzie, did you even

watch our last film?

It's about a frog

who marries a beautiful, perfect pig.

And they have to kiss each other a lot!

I don't think Americans

watch subtitled films.

Kermit, how about the Muppets

go on a world tour?

That's perfect!

I thought it was the end

But no, my friends, this is when

We get to do it all again!

Until the credits roll

We've got another go to show them

We can do it all again!

We're doing a sequel

It's more of the same

Let's give it a name

How about The Muppets Again?

It's the Muppets again

with The Muppets Again

It's the

Muppets

Again!

- Okay?

- I'm okay!

Okay!

Enema-boomed.!

Hey! Pepperoni!

Come on!

Let's dance.

It's time to light the lights.

Muppet news flash.

Constantine, the world's

most dangerous frog,

has escaped from

a maximum security gulag

in Siberia, Russia.

This move

has leapfrogged Constantine

to the number one

most wanted criminal in the world,

one place ahead

of the mysterious Lemur.

Wow.

Thanks for seeing me

at my regular booth, Muppets.

Big fan. Huge.

Dominic. International tour manager.

"Dominic Badguy"?

It's pronounced "Bad-gee." It's French.

It means "good man."

Oh, yes.

Listen up.

You're hot. You're having a moment.

But what is inevitable

about a moment? it ends.

I don't want this moment to end!

That's why we got to get out there now

A-ha!

Eh?

"Booby Traps"?

Ah...

Oh, there you are, my lovely.

Hmm! What's that?

Take the book?

I don't mind if I do.

At last, it is mine.

Finally, you are mine.

All right. Let's do this. Bare knuckles.

Bring it on, skinny. You don't scare me.

You got any sevens?

Go fish.

Is that all you got?

Ooh.

Hmm.

Man, this is way overdue.

"Once upon a time, under the sea,

"there was a little town

called Bikini Bottom.

"In this town, there was a place

called The Krusty Krab,

"where folks would come to eat a thing

called the Krabby Patty.

"Every greasy spoon has a fry cook,

and the one who worked here

"was named SpongeBob SquarePants."

Who lives in a pineapple under the sea?

SpongeBob SquarePants!

Absorbent and yellow and porous is he

SpongeBob SquarePants!

If nautical nonsense

be something you wish

SpongeBob SquarePants!

Then drop on the deck

and flop like a fish

SpongeBob SquarePants!

Stop!

Huh?

There's only one thing worse

than talking birds, and that would be...

Singing birds!

Okay, I promise not to

si-i-i-ng

Take it from us.

He really does hate singing birds.

Just keep weading.

Pwease, Mr. Piwate, sir.

Come closer

while I tell you the tale.

- Okay, start reading.

- No. Not that close!

Yeah. Hmm.

All right, here we go.

Now, SpongeBob loved his job

as a fry cook...

...more than anything.

And that is saying a lot

because he loved everything!

He loved his pet snail, Gary.

He loved his best friend, Patrick.

He loved blowing bubbles

- and jellyfishing.

- Whee!

He loved making Krabby Patties

for the folks of Bikini Bottom

just as much as they loved eating them.

Why, you may ask,

do they love this

greasy little sandwich so much?

Why did they eat them

for breakfast...

...lunch,

and dinner,

despite their doctor's warnings?

He'll be gone in a week.

Oh, Harold!

Oh. It was a secret.

No one was sure what was in these patties

that made them so delicious.

And, frankly, no one cared,

- except for Plankton.

- Meh.

Plankton owned a restaurant

right across the street

from The Krusty Krab,

where no one ate

because the food

was really bad.

Now, is that really necessary?

Plankton had made it his life's work

to steal the recipe.

SpongeBob, please, let's talk about this!

And SpongeBob was

always there to protect it.

But today, things

would be different.

Good morning, SpongeBob!

Morning, Patrick!

You here for

your pre-lunch Krabby Patty?

I'm getting two today.

One for me and one for my friend.

Oh. Have I met this friend?

"You know me, SpongeBob."

Enjoy, Patrick's tummy.

Thirteen,

fourteen, fifteen...

Hey, Mr. Krabs, I thought we got

our tartar sauce delivery on Thursday.

Tartar...

Sauce?

Bull's-eye!

Plankton!

So it's a food fight he wants, eh?

Welcome to Air Plankton.

Please put your seat backs

and tray tables up

as we're now approaching

our final destination.

Okay, Patrick, load the potatoes!

Mashed or scalloped, sir?

No, Patrick. Raw.

Sir, yes, sir!

Locked and loaded!

Don't worry, little formuler,

you'll be safe in this,

uh, safe.

Fire!

Potatoes?

He's closing in!

I think we have a few minutes

before he gets here.

He's right on top of us!

Hey, it's raining fries!

It's gonna take a lot more than potatoes

to bring this baby down.

Or maybe not.

Whoo!

Wait a minute, Patrick, look!

He's got a tank!

Well, Krabs, you're certainly

in a pickle now!

Hey, it's raining pickles!

Now it's raining...

Tanks.

You're welcome!

Finland.

Your orders, sir!

I'll have two

Krabby Patties-extra ketchup,

extra mustard, and hold the mayo.
"""

import random

ngrams = []

for b in range(len(text) - 4):
  ngrams.append(text[b:b+4])

random.shuffle(ngrams)
seed = random.choice(ngrams)

new_text = seed

for i in range(500):
  for n in ngrams:
    if (n[:3] == new_text[-3:]):
      new_text += n[-1]
      ngrams.remove(n)

print(new_text)

seed

st = "Grinch"

st[-3:]

alist = ["2","fnsdon","fnsdonamdsinwd"]

alist[0:2]

!pip install markovify

import markovify

text_model = markovify.Text(text)

novel = ""

for i in range(6000):
    sentence = text_model.make_sentence()
    
    novel += str(sentence)

len(novel.split(" "))

novel

# Install WeasyPrint version 52.5
!pip install weasyprint==52.5

# Import markdown, weasyprint, and several modules of weasyprint
import markdown
from weasyprint import HTML, CSS
from weasyprint.fonts import FontConfiguration

html = markdown.markdown(novel)

# prepare WeasyPrint
font_config = FontConfiguration()
rendered_html = HTML(string=html)

# The following bit of CSS formats the content of the pages, adding
# page numbers. Here's a good overview of the options:
# https://www.quackit.com/css/at-rules/css_page_at-rule.cfm 

css = CSS(string='''
@import url('https://fonts.googleapis.com/css2?family=Festive&display=swap');

@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap');
body {
font-family: 'Merriweather', serif;
}

hr {
  break-after: recto; 
}

h1 {
  font-size: 50pt;
  text-align:center;
  margin-top: 3in;
  font-family: 'Festive',cursive;
}
h2{
  break-before: recto;
  font-family: 'Festive',cursive;
}

h3 {
  font-size: 20pt;
  text-align:center;
}

/* set the basic page geometry and start the incrementer */
@page {
  font-family: 'Merriweather', serif;
  margin: 1in;
  size: letter;
  counter-increment: page;
  @bottom-center {
    content: "Laugh Track";
    text-align:center;
    font-style: italic;
    color: #666666;
  }
}

/* print the page number on the bottom-right of recto pages */
@page :right {
  @bottom-right{
    content: "[" counter(page) "]";
    text-align:right;
    color: #666666;
    visibility: invisible;
  }
}

/* print the page number on the bottom-left of verso pages */
@page :left {
  @bottom-left{
    content: "[" counter(page) "]";
    text-align:left;
    color: #666666;
  }
}

/* blank the footer on the first page */
@page:first{
  @bottom-left {content: ""}
  @bottom-right {content: ""}
  @bottom-center {content: ""}
}


''', font_config=font_config)

# Finally, this creates a PDF called "sample.pdf" with all the above settings
rendered_html.write_pdf('/content/sample.pdf', stylesheets=[css],font_config=font_config)